# Generated by Django 3.2.7 on 2021-09-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
